version: "3.9"

services:
  backend:
    image: local
    build: .
    container_name: backend
    env_file:
      - .env
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"

  celery:
    command: bash -c "celery -A settings worker -l INFO --autoscale=0,10"
    image: currency-backend
    stdin_open: true
    tty: true
    build: .
    container_name: celery
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - backend

  celery-beat:
    command: bash -c "celery -A settings beat -l INFO"
    image: currency-backend
    stdin_open: true
    tty: true
    build: .
    container_name: celery-beat
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - backend
      - celery

  memcached:
    image: memcached:1.6.21-alpine
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.12.4-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persisten=True
    environment:
      - CELERY_BROKER_URL=http://my-broker-url
      - FLOWER_PORT=8888
    ports:
      - "8888:8888"

networks:
  pg-network:

volumes:
  db_data:
