# Generated by Django 4.2.5 on 2023-09-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(choices=[('privatbank', 'PrivatBank'), ('another', 'Another Source')], max_length=255),
        ),
    ]
