# Generated by Django 4.2.3 on 2023-07-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default=1, max_length=68),
            preserve_default=False,
        ),
    ]
